# Generated by Django 2.2.13 on 2020-06-17 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20200616_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='zfasg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_zfasg', to=settings.AUTH_USER_MODEL),
        ),
    ]
